### ISSUE TITLE
Link to data

### ISSUE THREAD

**Issue by edawson** [NCBI-Codeathons/super-minityper#1]
We need links to several data sets:

1. SV calls and graph for human data, + matched reads

Suggestion: GIAB HG002

2. Metagenome readset containing structural variants (e.g. E. coli or yeast)

Mock microbial is one possibility: https://github.com/LomanLab/mockcommunity

**Comment by edawson** [comment]
GIAB HG002 variant calls: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz

Uploaded as unzipped VCF to dnanexus

**Comment by tijyojwad** [comment]
I'm upload the loman lab dataset. might take a while coz it's large and downloading it first onto the worker machine is taking a while

**Comment by Fu-Yilei** [comment]
SRR7415638 is a metagenome dataset of Saccharomyces cerevisiae.
https://lomanlab.github.io/mockcommunity/
